- name: Deploy frontend and backend containers from GitHub
  hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/sruthibv/3-tier-project.git"
    app_path: "/root/3tier-ansible/"
    frontend_image: "frontend-app:latest"
    backend_image: "backend-app:latest"
    rds_host: "database-1.cvsqoacmkw59.us-east-1.rds.amazonaws.com"
    rds_user: "admin"
    rds_password: "admin123"
    rds_port: "3306"

  roles:
    - common
    - gitclone
    - frontend
    - backend

