- name: Deploy frontend and backend containers from GitHub
  hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/Subratp12/2nd10WeeksofCloudOps-main.git"
    app_path: "/root/sp/"
    frontend_image: "frontend-app:latest"
    backend_image: "backend-app:latest"
    rds_host: "database-2.cvsqoacmkw59.us-east-1.rds.amazonaws.com"
    rds_user: "admin"
    rds_password: "admin123"
    rds_port: "3306"

  roles:
    - common
    - gitclone
    - backend
    - frontend

